# Generated by Django 3.0.5 on 2020-04-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrowed',
            new_name='borrower',
        ),
    ]
